apiVersion: v1
kind: ConfigMap
metadata:
  name: talki-config
  namespace: talki
  labels:
    app: talki-application
data:
  # Spring Boot configuration
  SPRING_PROFILES_ACTIVE: "kubernetes"
  SERVER_PORT: "8080"
  GRPC_SERVER_PORT: "9090"
  
  # Database configuration
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/talki_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul"
  SPRING_DATASOURCE_USERNAME: "talki1234"
  
  # Kafka configuration
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  
  # JPA configuration
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "false"
  
  # Logging configuration
  LOGGING_LEVEL_COM_LANGHAKERS_TALKI: "INFO"
  LOGGING_FILE_NAME: "/app/logs/talki-application.log"

