apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: talki
  labels:
    app: mysql
    component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
        component: database
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: talki-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          value: "talki_db"
        - name: MYSQL_USER
          value: "talki1234"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: talki-secret
              key: MYSQL_PASSWORD
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        - name: mysql-init
          mountPath: /docker-entrypoint-initdb.d
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: mysql-init
        configMap:
          name: mysql-init-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: talki
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-config
  namespace: talki
  labels:
    app: mysql
data:
  01-init.sql: |
    -- MySQL initialization script for Talki application
    CREATE DATABASE IF NOT EXISTS talki_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    USE talki_db;
    GRANT ALL PRIVILEGES ON talki_db.* TO 'talki1234'@'%';
    FLUSH PRIVILEGES;

